#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "Error: Must supply exactly one argument with the image tag, got ${#} args"
    exit 1
fi

TAG="$1"
docker build --tag "ghcr.io/slarwise/image-api:${TAG}" .
