on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  packages: write
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: ./scripts/build-image "$GITHUB_REF_NAME"
      - name: Push image
        run: ./scripts/push-image "$GITHUB_REF_NAME"
