on:
  push:
    tags:
      - '*'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout/issues/1471
          fetch-depth: 0
          fetch-tags: true
      - name: Get the current tag
        run: |
          TAG="$(git tag --contains HEAD)"
          echo "TAG=${TAG}" >> "$GITHUB_ENV"
      - name: Build image
        run: ./scripts/build-image "$TAG"
      - name: Push image
        run: ./scripts/push-image "$TAG"
